In [0]:
# Liberar o acesso as pastas do meu Google Drive.
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [0]:
# Imporar a biblioteca Pandas para manipular o dataset.
import pandas as pd

In [0]:
# Ler e mostrar o inicio do data set o dataset.
treino = pd.read_csv("/content/drive/My Drive/ML/orange_small_train.data", sep ='\t')
treino.head()

In [0]:
# Ler o alvo(target).
appetency = pd.read_csv("http://www.vincentlemaire-labs.fr/kddcup2009/orange_small_train_appetency.labels")
appetency.head()

In [0]:
# Conferir o tamanho do dataset.
treino.shape

In [0]:
# Estatisticas basicas do dataset.
treino.describe()

In [0]:
# Contagem dos NA por coluna.
treino.isnull().sum()

In [0]:
# Trocar os NA pela média.
treino = treino.fillna(treino.mean())

In [0]:
#Conferindo a troca de NA pela média.
treino.describe()

               Var1          Var2           Var3  ...         Var190  Var209  Var230
count  50000.000000  50000.000000   50000.000000  ...   50000.000000     0.0     0.0
mean      11.487179      0.004029     425.298387  ...   22007.045192     NaN     NaN
std        4.820354      0.022352     672.206258  ...    2370.061624     NaN     NaN
min        0.000000      0.000000       0.000000  ...       0.000000     NaN     NaN
25%       11.487179      0.004029     425.298387  ...   22007.045192     NaN     NaN
50%       11.487179      0.004029     425.298387  ...   22007.045192     NaN     NaN
75%       11.487179      0.004029     425.298387  ...   22007.045192     NaN     NaN
max      680.000000      5.000000  130668.000000  ...  230427.000000     NaN     NaN

[8 rows x 192 columns]